sudo: required
dist: trusty
services:
- redis-server
- mysql
before_install:
- sudo apt-get -qqy update
- git submodule update --init --recursive
install:
- bash build.sh
before_script:
- echo ""
script:
- echo ""
notifications:
  slack:
    secure: hw9JNYs3VwMbxC5AvzU4v0GNol1/k2Sl6oLSxaGhq60BYXYB23PgJlu6fg5NlAkVXlu4DYPyj9a2VTTTXm+WznXz3qDXQz382/3TOnwm/i4F72mJUvogsZUfXSiPWbrPi/+fbw3LIcngwDjirV9lO0hsRAZycpljQ6Huz5PSu8TfGLPSmNfnStssXjIKz14Qltle6fQvkCX9zmgsd+WyWDxsSctJFIEXBElTEv9sA9Kq/Aa3qrN5G5vfgswpIghlMPNonnltt19au06FjjRJc6JsuDchHmV/mI2diQ4nRhCL8TMTwyGSMe/JGY8cRkvYGoB3z+37gqHvowiJvqQXNAWZZSfIxMEhNsNmSKHA2B6WPvDpo/t3xZ0edzTJnrpwSJazAW2TavLVOPRWJPNuc8j8bN+WscbWUz9SHRJc2uRBsKbgokC4mK9Dz/VkrEXAjc4I9q+uchbpJfhvI6XO50iPIC+/vHg8VrQ3GcUEJK2TEIMsKx43E/7ijR3r443RZ/71uveFLnPubRu8vpKyOeiHlOg2jJocr5WENnEMccyWQgm9uDpEyHUJzgJg8j2PRcfrFQgFgtUxDqMrjFDGlpgI5uhOoZ4ftqn+bY8iuD4nROiEgy9LCH0/fPSLzgASdsKXEPzgmzeGpS3UF//W+UHv4fT6YUsS8Y3Tpy/45v0=
